### ISSUE TITLE
Extract .sync method and create a separate module (like "bin-check-sync")

### ISSUE THREAD

**Issue by shinnn** [kevva/bin-check#3]
Because:

1. I don't want to see the logs of [spawn-sync](https://github.com/ForbesLindesay/spawn-sync)'s [`postinstall` script]() though I never use the `.sync` method.
2. spawn-sync package is quite big (about 0.5 MB :fearful:).

    ```
    $ npm install spawn-sync
    $ du -sh node_modules/spawn-sync
    > 468K	node_modules/spawn-sync
    ```

This would probably have a positive impact on https://github.com/imagemin/imagemin/issues/97.

**Comment by sindresorhus** [comment]
Just remove the `sync` method. Using sync is an anti-pattern anyways.

Alternatively, I have https://github.com/sindresorhus/exec-file-sync which have none of these problems.

**Comment by shinnn** [comment]
Yeah, just removing the `sync` method seems the best solution for me.

**Comment by kevva** [comment]
+1.
